apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis
    role: service
  name: redis
  namespace: cx-stores-dispositionmanager-perf
spec:
  clusterIP: 
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    name: redis
  sessionAffinity: None
  type: ClusterIP
